apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pwi73mq2u-python
  janus-idp.io/tekton: pwi73mq2u-python
  backstage.io/kubernetes-id: pwi73mq2u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pwi73mq2u-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
